

library(tidyverse)

dir0 = "/media/akira/LeGris4h/250609_FragPipeAnalystR_1.1.0_MaxLFQ_250527"
dir1 = file.path(dir0, "consensus")
dirFA = file.path(dir1, "FASTA_LFQ_quantiles")

file = "df_bpca_peptide_phosphoMAP.csv"
df = read.csv(file.path(dir1, file))

### Set a filter for the phospho co-occurrence pattern of pY-notpT-notpS
# The dataframe has been tagged for pTyr, pThr, and pSer, which are then combined for co-occurrence in the column "Combination"
# The phospho pattern '100' is chosen based on the bar plots generated by A2_Annotate_df_peptides_w_phospho_modifications
df_100 = df %>%
  filter(Combination == "100")

### Set up filters for log2 Avg_MaxLFQ_Intensity
# Function to prepare log2-transformed long-format data
prepare_log2_filtered_peptides <- function(df, 
                                           filter_condition = NULL, 
                                           groups = NULL, 
                                           quantile_range = c(0, 1)) {
  # Apply optional filter condition
  if (!is.null(filter_condition)) {
    df <- df %>% filter(!!rlang::parse_expr(filter_condition))
    if (nrow(df) == 0) return(NULL)
  }
  
  # Identify intensity columns
  avg_cols <- grep("_Avg_MaxLFQ_Intensity$", names(df), value = TRUE)
  df[avg_cols] <- lapply(df[avg_cols], function(x) ifelse(x == 0, NA, x))
  
  # Log2 transform
  log2_df <- log2(df[avg_cols])
  log2_df$Peptide_Sequence <- df$Peptide_Sequence  # retain peptide info
  
  # Pivot longer
  log2_long <- pivot_longer(log2_df, 
                            cols = -Peptide_Sequence, 
                            names_to = "Group", 
                            values_to = "Log2_Intensity")
  log2_long$Group <- gsub("_Avg_MaxLFQ_Intensity", "", log2_long$Group)
  
  # Filter by group(s) if specified
  if (!is.null(groups)) {
    log2_long <- log2_long %>% filter(Group %in% groups)
  }
  
  # Apply quantile filter
  q_low <- quantile(log2_long$Log2_Intensity, probs = quantile_range[1], na.rm = TRUE)
  q_high <- quantile(log2_long$Log2_Intensity, probs = quantile_range[2], na.rm = TRUE)
  log2_long <- log2_long %>% 
    filter(Log2_Intensity >= q_low, Log2_Intensity <= q_high)
  
  return(na.omit(log2_long))
}

# Get peptides from GroupA and GroupB in the top 25% of log2 intensity
#filtered_data <- prepare_log2_filtered_peptides(
#  df = my_data,
#  groups = c("GroupA", "GroupB"),
#  quantile_range = c(0.75, 1)
#)

#### Get Peptide_Sequence with the pY-notpT-notpS phospho pattern on log2 scale with a low cut filter of 5%
p100peptide_0.05_1 = prepare_log2_filtered_peptides(
  df = df_100,
  groups = c("P8E2", "P8E2_T338I", "P8E2_T338M", "WT", "WT_T338I", "WT_T338M"),
  quantile_range = c(0.05, 1)
)

#### Make fasta file for "Peptide_Sequence" in each with header of > "Gene" | "Protein_ID" | "Description. 
# Function to write a dataframe to a FASTA file
write_fasta <- function(df, file_name) {
  lines <- apply(df, 1, function(row) {
    header <- paste0(">", row["Protein_ID"], " | ", row["Gene"], " | ", row["Description"])
    sequence <- row["Peptide_Sequence"]
    c(header, sequence)
  })
  writeLines(unlist(lines), con = file_name)
}

# Use the write_fasta function for each group

groups = unique(p100peptide_0.05_1$Group)

for (grp in groups) {
  # Step 1: Filter for current group
  group_peptides <- p100peptide_0.05_1 %>%
    filter(Group == grp) %>%
    pull(Peptide_Sequence) %>%
    unique()
  
  # Step 2: Subset original df for annotation info
  fasta_input <- df %>%
    filter(Peptide_Sequence %in% group_peptides) %>%
    select(Protein_ID, Gene, Description, Peptide_Sequence) %>%
    distinct()
  
  # Step 3: Write to FASTA
  file_name <- paste0("pYnotpTnotpS_peptide_", grp, ".fasta")
  write_fasta(fasta_input, file.path(dirFA, file_name))
}

